import type { Metadata } from "next";
import "./globals.css";
import NavMenu from "@/components/NavMenu/NavMenu";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Header />
        <div className="flex">
          <NavMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
