import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import { domAnimation, LazyMotion } from "framer-motion";
import { Public_Sans } from "next/font/google";
import HeaderTop from "@/components/Header/HeaderTop";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={publicSans.className}>
      <LazyMotion features={domAnimation}>
        <body>
          <Header />
          <div className="flex-1 flex-col">
            <HeaderTop />
            {children}
          </div>
        </body>
      </LazyMotion>
    </html>
  );
}
